apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumBGPPeerConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2alpha1","kind":"CiliumBGPPeerConfig","metadata":{"annotations":{},"name":"cluster-peer"},"spec":{"ebgpMultihop":2,"families":[{"advertisements":{"matchLabels":{"advertise":"bgp"}},"afi":"ipv4","safi":"unicast"}],"gracefulRestart":{"enabled":true,"restartTimeSeconds":120},"timers":{"holdTimeSeconds":30,"keepAliveTimeSeconds":10}}}
    creationTimestamp: "2026-04-22T12:58:51Z"
    generation: 2
    name: cluster-peer
    resourceVersion: "326106"
    uid: c62a900a-2b8e-4096-9b07-da12b0c32ff0
  spec:
    ebgpMultihop: 2
    families:
    - advertisements:
        matchLabels:
          advertise: bgp
      afi: ipv4
      safi: unicast
    gracefulRestart:
      enabled: true
      restartTimeSeconds: 120
    timers:
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 30
      keepAliveTimeSeconds: 10
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T12:58:51Z"
      message: ""
      observedGeneration: 2
      reason: MissingAuthSecret
      status: "False"
      type: cilium.io/MissingAuthSecret
kind: List
metadata:
  resourceVersion: ""
