apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumBGPAdvertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2alpha1","kind":"CiliumBGPAdvertisement","metadata":{"annotations":{},"labels":{"advertise":"bgp"},"name":"lb-vip-advertisement"},"spec":{"advertisements":[{"advertisementType":"Service","selector":{},"service":{"addresses":["LoadBalancerIP"]}}]}}
    creationTimestamp: "2026-04-22T12:58:51Z"
    generation: 3
    labels:
      advertise: bgp
    name: lb-vip-advertisement
    resourceVersion: "327005"
    uid: 80c4f65a-d522-4e81-b4a5-8207becd9d85
  spec:
    advertisements:
    - advertisementType: Service
      selector: {}
      service:
        addresses:
        - LoadBalancerIP
kind: List
metadata:
  resourceVersion: ""
