apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-1
  containers:
  - name: curl
    image: curlimages/curl:8.10.1
    command: ["sleep","3600"]
  restartPolicy: Never
